# fly.toml app configuration file generated for markdown-editor-8kmqhw on 2025-05-09T15:26:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'markdown-editor-8kmqhw'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
